theme: jekyll-theme-minimal
title: hfly2019 的主页
description: 欢迎来到我的个人网站

# 博客配置
permalink: /posts/:title/
defaults:
  - scope:
      path: "posts"
      type: "posts"
    values:
      layout: post
      _comments:
        date: "自动生成"